// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using JiraProject.DAL.Context;

namespace JiraProject.DAL.Migrations
{
    [DbContext(typeof(TestProjectContext))]
    partial class TestProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JiraProject.DAL.Entities.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CrtDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrtUserID")
                        .HasColumnType("int");

                    b.Property<string>("CrtUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdUserID")
                        .HasColumnType("int");

                    b.Property<string>("UpdUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CrtDate = new DateTime(2022, 5, 1, 19, 32, 43, 863, DateTimeKind.Local).AddTicks(6586),
                            CrtUserID = 0,
                            CrtUserIP = "0",
                            Desc = "Seeding-Data",
                            IsActive = true,
                            MachineName = "DESKTOP-0000",
                            Name = "INTRANET Yazılım Teknolojileri",
                            RegistrationNumber = "0",
                            Type = "1",
                            UpdDate = new DateTime(2022, 5, 1, 19, 32, 43, 864, DateTimeKind.Local).AddTicks(6660),
                            UpdUserID = 0,
                            UpdUserIP = "0"
                        });
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CrtDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrtUserID")
                        .HasColumnType("int");

                    b.Property<string>("CrtUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdUserID")
                        .HasColumnType("int");

                    b.Property<string>("UpdUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.MenuRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CrtDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrtUserID")
                        .HasColumnType("int");

                    b.Property<string>("CrtUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<int?>("RolesID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdUserID")
                        .HasColumnType("int");

                    b.Property<string>("UpdUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRoleID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RolesID");

                    b.ToTable("MenuRole");
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.ParameterDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CrtDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrtUserID")
                        .HasColumnType("int");

                    b.Property<string>("CrtUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParameterMasterID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdUserID")
                        .HasColumnType("int");

                    b.Property<string>("UpdUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ParameterMasterID");

                    b.ToTable("ParameterDetail");
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.ParameterMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CrtDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrtUserID")
                        .HasColumnType("int");

                    b.Property<string>("CrtUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdUserID")
                        .HasColumnType("int");

                    b.Property<string>("UpdUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ParameterMaster");
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.Roles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CrtDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrtUserID")
                        .HasColumnType("int");

                    b.Property<string>("CrtUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdUserID")
                        .HasColumnType("int");

                    b.Property<string>("UpdUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("MenuID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyID = 1,
                            CrtDate = new DateTime(2022, 5, 1, 19, 32, 43, 866, DateTimeKind.Local).AddTicks(3948),
                            CrtUserID = 0,
                            CrtUserIP = "0",
                            Desc = "TEST",
                            IsActive = true,
                            MachineName = "DESKTOP-0000",
                            Name = "Yazılım Geliştirici",
                            UpdDate = new DateTime(2022, 5, 1, 19, 32, 43, 866, DateTimeKind.Local).AddTicks(3958),
                            UpdUserID = 0,
                            UpdUserIP = "0"
                        });
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CrtDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrtUserID")
                        .HasColumnType("int");

                    b.Property<string>("CrtUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdUserID")
                        .HasColumnType("int");

                    b.Property<string>("UpdUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyID = 1,
                            CrtDate = new DateTime(2022, 5, 1, 19, 32, 43, 867, DateTimeKind.Local).AddTicks(505),
                            CrtUserID = 0,
                            CrtUserIP = "0",
                            Email = "berkcolak4@gmail.com",
                            IsActive = true,
                            MachineName = "DESKTOP-0000",
                            Password = "123456",
                            Phone = "5434203403",
                            UpdDate = new DateTime(2022, 5, 1, 19, 32, 43, 867, DateTimeKind.Local).AddTicks(514),
                            UpdUserID = 0,
                            UpdUserIP = "0",
                            UserName = "Berk Çolak"
                        },
                        new
                        {
                            ID = 2,
                            CompanyID = 1,
                            CrtDate = new DateTime(2022, 5, 1, 19, 32, 43, 867, DateTimeKind.Local).AddTicks(1569),
                            CrtUserID = 0,
                            CrtUserIP = "0",
                            Email = "test@test.com.tr",
                            IsActive = true,
                            MachineName = "DESKTOP-0000",
                            Password = "123456",
                            Phone = "123456",
                            UpdDate = new DateTime(2022, 5, 1, 19, 32, 43, 867, DateTimeKind.Local).AddTicks(1573),
                            UpdUserID = 0,
                            UpdUserIP = "0",
                            UserName = "Test Test"
                        },
                        new
                        {
                            ID = 3,
                            CompanyID = 1,
                            CrtDate = new DateTime(2022, 5, 1, 19, 32, 43, 867, DateTimeKind.Local).AddTicks(1649),
                            CrtUserID = 0,
                            CrtUserIP = "0",
                            Email = "test2@test.com.tr",
                            IsActive = true,
                            MachineName = "DESKTOP-0000",
                            Password = "123456",
                            Phone = "123456",
                            UpdDate = new DateTime(2022, 5, 1, 19, 32, 43, 867, DateTimeKind.Local).AddTicks(1651),
                            UpdUserID = 0,
                            UpdUserIP = "0",
                            UserName = "Test Test"
                        });
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.UserRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CrtDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrtUserID")
                        .HasColumnType("int");

                    b.Property<string>("CrtUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int?>("RolesID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdUserID")
                        .HasColumnType("int");

                    b.Property<string>("UpdUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("RolesID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyID = 1,
                            CrtDate = new DateTime(2022, 5, 1, 19, 32, 43, 867, DateTimeKind.Local).AddTicks(4634),
                            CrtUserID = 0,
                            CrtUserIP = "0",
                            Desc = "TEST",
                            IsActive = true,
                            MachineName = "DESKTOP-0000",
                            RoleID = 1,
                            StartDate = new DateTime(2022, 5, 1, 19, 32, 43, 867, DateTimeKind.Local).AddTicks(5522),
                            UpdDate = new DateTime(2022, 5, 1, 19, 32, 43, 867, DateTimeKind.Local).AddTicks(4640),
                            UpdUserID = 0,
                            UpdUserIP = "0",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.UserToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CrtDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrtUserID")
                        .HasColumnType("int");

                    b.Property<string>("CrtUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdUserID")
                        .HasColumnType("int");

                    b.Property<string>("UpdUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.Menu", b =>
                {
                    b.HasOne("JiraProject.DAL.Entities.Company", null)
                        .WithMany("Menu")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.MenuRole", b =>
                {
                    b.HasOne("JiraProject.DAL.Entities.Roles", null)
                        .WithMany("MenuRole")
                        .HasForeignKey("RolesID");
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.ParameterDetail", b =>
                {
                    b.HasOne("JiraProject.DAL.Entities.ParameterMaster", null)
                        .WithMany("ParameterDetail")
                        .HasForeignKey("ParameterMasterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.Roles", b =>
                {
                    b.HasOne("JiraProject.DAL.Entities.Company", null)
                        .WithMany("Roles")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JiraProject.DAL.Entities.Menu", null)
                        .WithMany("Roles")
                        .HasForeignKey("MenuID");
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.User", b =>
                {
                    b.HasOne("JiraProject.DAL.Entities.Company", null)
                        .WithMany("User")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.UserRole", b =>
                {
                    b.HasOne("JiraProject.DAL.Entities.Company", null)
                        .WithMany("UserRole")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JiraProject.DAL.Entities.Roles", null)
                        .WithMany("UserRole")
                        .HasForeignKey("RolesID");

                    b.HasOne("JiraProject.DAL.Entities.User", null)
                        .WithMany("UserRole")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.UserToken", b =>
                {
                    b.HasOne("JiraProject.DAL.Entities.User", null)
                        .WithMany("UserToken")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.Company", b =>
                {
                    b.Navigation("Menu");

                    b.Navigation("Roles");

                    b.Navigation("User");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.Menu", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.ParameterMaster", b =>
                {
                    b.Navigation("ParameterDetail");
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.Roles", b =>
                {
                    b.Navigation("MenuRole");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("JiraProject.DAL.Entities.User", b =>
                {
                    b.Navigation("UserRole");

                    b.Navigation("UserToken");
                });
#pragma warning restore 612, 618
        }
    }
}
